title: The Lampinen Organization
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3743287
  brandStrength: 0.6364124
  lightness: 0.25
  brandColors:
    - '#160C0A'
    - '#B9C2D1'
    - '#5E4A31'
    - '#E3A143'
    - '#E9F2FA'
  rhythmicContrast: 0.3088077
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: lampinen
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9120842742267996
layout_spectrum: 0.94096
