name: lampinen
favicon: null
layout_spectrum: 0.34131305711343884
typography_spectrum: 0.9120842742267996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131218'
    - '#96662a'
    - '#c6b297'
    - '#e6ad00'
    - '#ece4cd'
  brandStrength: 0.8756866769399494
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.30761481053195894
purpose: []
