name: lampinen
favicon: null
layout_spectrum: 0.34131305711343884
typography_spectrum: 0.9120842742267996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8756866769399494
  lightness: 0.8811394355725497
  saturation: 0.08753759576939046
  rhythmicContrast: 0.30761481053195894
purpose: []
